export const EVENTS=[
 ['robo-race','Robo Race','01','#59e7ff','Images/robo-race.webp','SPEED / CONTROL','Speed, precision and disciplined control.'],
 ['robo-tug','Robo Tug of War','02','#8f7cff','Images/robo-tug.webp','TORQUE / TRACTION','Traction, torque and strategic control.'],
 ['robo-war','Robo War','03','#ff5f87','Images/robo-war.webp','TACTICS / IMPACT','Engineering decisions meet arena tactics.'],
 ['robo-soccer','Robo Soccer','04','#c9ff4a','Images/robo-soccer.webp','DEMO / MOTION','A demonstration of robotic movement and control.']
];
const FALLBACK_HEADER=`<header id="siteHeader"><nav class="nav"><a class="brand" href="index.html"><img src="assets/awes-logo.png" alt="AWES"><span>ROBOKRITI</span><i></i></a><div class="links"><a data-nav="home" href="index.html">Home</a><a data-nav="events" href="events.html">Arena</a><a data-nav="rules" href="rules.html">Rules</a><a data-nav="registration" href="registration.html">Register</a><a data-nav="announcements" href="announcements.html">Updates</a><a data-nav="results" href="results.html">Results</a><a data-nav="faq" href="faq.html">FAQ</a><a data-nav="about" href="about.html">About</a><a data-nav="contact" href="contact.html">Contact</a></div><a class="navCta" href="registration.html">JOIN THE ARENA ↗</a><button id="menuBtn" aria-label="Menu"><span></span><span></span></button></nav></header><div id="mobileMenu"><div class="mobileInner"><span class="mono">ROBOKRITI / NAVIGATION</span><div><a href="index.html">Home</a><a href="events.html">Arena</a><a href="rules.html">Rules</a><a href="registration.html">Register</a><a href="announcements.html">Updates</a><a href="results.html">Results</a><a href="faq.html">FAQ</a><a href="about.html">About</a><a href="contact.html">Contact</a></div><span class="mono">ARMY PUBLIC SCHOOL · LBS MARG · LUCKNOW</span></div></div>`;
const FALLBACK_FOOTER=`<footer><div class="wrap footerGrid"><div><a class="footerLogo" href="index.html">ROBO<br><i>KRITI</i></a><p>Inter-class robotics competition at Army Public School, Lal Bahadur Shastri Marg, Lucknow.</p></div><div><span class="mono">EXPLORE</span><div class="footerLinks"><a href="events.html">Arena</a><a href="rules.html">Rules</a><a href="registration.html">Registration</a><a href="announcements.html">Announcements</a><a href="results.html">Results</a><a href="faq.html">FAQ</a><a href="about.html">About</a><a href="contact.html">Contact</a></div></div><div><span class="mono">EVENT SIGNAL</span><div class="signal"><i></i><b>REGISTRATION OPEN</b><span>UNTIL 03 SEP · 11:59 PM IST</span></div><a class="mail" href="mailto:ayusshh@outlook.in">ayusshh@outlook.in ↗</a></div></div><div class="wrap footerBottom"><span>© 2026 ROBOKRITI</span><span>ARMY PUBLIC SCHOOL · LBS MARG · LUCKNOW</span><span>BUILT FOR THE ARENA</span></div></footer>`;
export async function init(){
 const h=document.getElementById('header'),f=document.getElementById('footer');
 if(h){try{const r=await fetch('includes/header.html');h.innerHTML=r.ok?await r.text():FALLBACK_HEADER}catch{h.innerHTML=FALLBACK_HEADER}}
 if(f){try{const r=await fetch('includes/footer.html');f.innerHTML=r.ok?await r.text():FALLBACK_FOOTER}catch{f.innerHTML=FALLBACK_FOOTER}}
 const page=document.body.dataset.page;document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===page));
 nav(); cursor(); magnetic(); reveal();
}
function nav(){const h=document.getElementById('siteHeader'),m=document.getElementById('mobileMenu'),b=document.getElementById('menuBtn');let last=scrollY;b?.addEventListener('click',()=>m?.classList.toggle('open'));m?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>m.classList.remove('open')));addEventListener('scroll',()=>{if(!h)return;const y=scrollY;if(y>last+8&&y>120)h.classList.add('hidden');else if(y<last-8)h.classList.remove('hidden');last=y},{passive:true})}
function cursor(){const c=document.querySelector('.cursor');if(!c||matchMedia('(pointer:coarse)').matches)return;let x=innerWidth/2,y=innerHeight/2,tx=x,ty=y;addEventListener('pointermove',e=>{tx=e.clientX;ty=e.clientY;c.classList.add('ready')},{passive:true});const loop=()=>{x+=(tx-x)*.16;y+=(ty-y)*.16;c.style.left=x+'px';c.style.top=y+'px';requestAnimationFrame(loop)};loop();document.addEventListener('mouseover',e=>{if(e.target.closest('a,button,input,select,textarea,.eventCard,summary'))c.classList.add('big');else c.classList.remove('big')})}
function magnetic(){if(matchMedia('(pointer:coarse)').matches)return;document.querySelectorAll('.magnetic,.navCta').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.10}px,${(e.clientY-r.top-r.height/2)*.10}px)`});el.addEventListener('pointerleave',()=>el.style.transform='')})}
export function cards(id){const el=document.getElementById(id);if(!el)return;el.innerHTML=EVENTS.map(e=>`<a class="eventCard" style="--accent:${e[3]}" href="${e[0]}.html"><img src="${e[4]}" alt="${e[1]}" loading="lazy"><div class="cardParticles"></div><span class="eventArrow">↗</span><div class="cardContent"><div class="num">${e[2]} / EVENT</div><h3>${e[1]}</h3><p>${e[6]}</p><div class="eventMeta"><span>${e[5]}</span><span>EXPLORE ↗</span></div></div></a>`).join('');el.querySelectorAll('.cardParticles').forEach(layer=>{for(let i=0;i<18;i++){const p=document.createElement('i');p.className='particle';p.style.left=Math.random()*100+'%';p.style.top=Math.random()*100+'%';p.style.animationDelay=(-Math.random()*5)+'s';layer.appendChild(p)}});tiltCards()}
function tiltCards(){if(matchMedia('(pointer:coarse)').matches)return;document.querySelectorAll('.eventCard').forEach(card=>{card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(1100px) rotateX(${y*-2.2}deg) rotateY(${x*2.2}deg) translateY(-8px)`});card.addEventListener('pointerleave',()=>card.style.transform='')})}
export function toast(text){let t=document.querySelector('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.appendChild(t)}t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
function reveal(){const els=document.querySelectorAll('.section,.pageHero,.eventCard,.message,.person,.feedItem,.dataBox,.glowCard');const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.08,rootMargin:'0px 0px -35px'});els.forEach(e=>io.observe(e))}
